### ISSUE TITLE
Auto start trouble

### ISSUE THREAD

**Issue by StDarton** [sanny32/OpenModSim#21]
`--config` key starts server (ModSim) but client (ModScan) with correct configuration gets `Illegal data address (0x02)` error on connection. 
When I update any configuration on server during this connection (just change any field to another value and back) everything starts to work fine.
I guess there is some initialization missing after server starts using `--config` key.
It is a pity this bug prevents using this great app as true MODBUS server.

**Comment by sanny32** [comment]
Hello @StDarton. Will test
