### ISSUE TITLE
auto connect after start the program

### ISSUE THREAD

**Issue by edwina95** [sanny32/OpenModSim#6]
how auto connect after start the program ?

**Comment by sanny32** [comment]
Hello @edwina95. There is no option to auto start connection after start program yet.

**Comment by edwina95** [comment]
request, that can start auto , can set port for tcp,  or select com , maybe via parameter  thank you.

**Comment by sanny32** [comment]
Okay, it will be in one of the future releases.

**Comment by sanny32** [comment]
Implemented at version 1.5.1 via` --config ` command line parameter.
You must save test config file via menu `File` when your program has connection. Load this test config file via ` --config ` command line parameter when program start.
